name: TagBot
on:
  issue_comment:
    types: [created]
jobs:
  TagBot:
    if: github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
